### ISSUE TITLE
Search start position

### ISSUE THREAD

**Issue by minad** [astoff/isearch-mb#1]
When putting the point at point-min, e.g., `;;; isearch-mb.el --- Alternative Isearch UI based on the minibuffer -*- lexical-binding: t; -*-` and entering Alternative, then Alternative will be found and highlighted. When deleting it again and searching for isearch, the second Isearch is highlighted. However I think the search should actually go back to the starting point when changing the search string.

**Comment by astoff** [comment]
I have noticed this... Uncommenting a line with `isearch-fallback` (it's already in the code) solves this; I wonder if it introduces some other issue.

Normal isearch has the same behavior if you bind `DEL` to `isearch-del-char` in `isearch-mode-map`. I would first try to fix this in isearch, and then see it iserach-mb needs something special.

**Comment by minad** [comment]
Great, with the fallback it works better! Thanks!
