### ISSUE TITLE
ELPA?

### ISSUE THREAD

**Issue by manuel-uberti** [astoff/isearch-mb#13]
Hi,

first of all thanks for this package. The README states that it is available from ELPA, but I cannot find it there.

![Screenshot from 2021-05-17 16-17-56](https://user-images.githubusercontent.com/8199224/118504101-85ba7c00-b72b-11eb-85ac-522107ba662c.png)

![Screenshot from 2021-05-17 16-18-50](https://user-images.githubusercontent.com/8199224/118504175-94a12e80-b72b-11eb-8c06-b6a6be66dcec.png)

Is it supposed to be available soon?

**Comment by astoff** [comment]
That's right. In fact, this repo has already been pulled into ELPA's, so I suppose it will take a day from now at most.

**Comment by manuel-uberti** [comment]
Thank you. We can close this then. :)
