### ISSUE TITLE
Recenter issue

### ISSUE THREAD

**Issue by Ergus** [astoff/isearch-mb#14]
Hi:

Trying the package I am getting some issues that the buffer sometimes scrolls when finalizing the search. It does not follow an specific pattern for me. But it seems like emacs tries to do a recenter when finalizing isearch. Have you observed something like that?

**Comment by astoff** [comment]
Now that you mentioned it, yes, I get the same behavior. The pattern I observe is that, whenever the original window scrolls, it's recentered when the minibuffer exits; and this actually happens for every command that uses the minibuffer.

I'm not sure which behavior I prefer, and this could possibly be a customization option. But so far I couldn't find a way to disable the recentering, which is happens automatically.

**Comment by Ergus** [comment]
Maybe we could ask to Juri or some other developer in the mailing list if there is a fix for this or a common workaround. In general I know that swiper had a similar issue some time ago. But is was associated with the the fact that `swiper` resizes the minibuffer but that's why there is the option `swiper-action-recenter`.

This needs to be fixed also because the default value for `recenter-redisplay` is `tty`, that calls redisplay when recenter, but in the terminal that makes the screen to flash which is very annoying.

**Comment by astoff** [comment]
I've pushed a fix. Thanks for the bug report, and let me know if you spot something awry.

**Comment by Ergus** [comment]
Sure! Thanks

**Comment by Ergus** [comment]
BTW:

IIRC if the package is in elpa a version increase is required to make the update available for `packages`. I don't know exactly how, but many packages use a tag like `20210521.1319` that is somehow autogenerated after a push in the github repo.

**Comment by astoff** [comment]
Yes, the autogenerated version numbers are a MELPA thing, in GNU ELPA one has to change the version number explicitly. But let's wait a couple of weeks to collect some more bugs :-).

**Comment by Ergus** [comment]
Swiper and other Elpa packages have the autogeneration somehow.
