### ISSUE TITLE
Avoid moving to the prompt.

### ISSUE THREAD

**Issue by Ergus** [astoff/isearch-mb#15]
Hi:

(this is just a detail, but as you requested for more bugs I add it).

When using the package if we use the arrows to move backward the prompt moves beyond the first search character. So over the `I-search` prompt. This is not a big issue, but the fix shouldn't be too complex.

**Comment by astoff** [comment]
> (this is just a detail, but as you requested for more bugs I add it).

Thanks!



>  This is not a big issue, but the fix shouldn't be too complex.

True, but this happens in any minibuffer session (just try it on `M-x`), so there's no point in fixing it here. What's a bit weird in isearch-mb (also on the vertical completion UIs) is that the count to the left of the prompt is an overlay, not the prompt itself.  So the beginning of buffer is neither at the very left of the screen, nor just right of the prompt string...
