### ISSUE TITLE
Enter non-incremental search on empty submission.

### ISSUE THREAD

**Issue by okamsn** [astoff/isearch-mb#16]
Hello,

In normal Isearch, an empty submission activates one of the `nonincremental-search-*` commands. This is helpful for larger files.

Please consider adding this feature to Isearch MB.

Thank you.

**Comment by astoff** [comment]
After considering this again, I think it's better to keep isearch just what it is (incremental), and just let RET always quit. There's space in the `M-s` prefix for other search commands.
