### ISSUE TITLE
isearch-mode-map issue

### ISSUE THREAD

**Issue by Ergus** [astoff/isearch-mb#17]
Hi I use isearch with swiper with a command swiper-isearch-toggle.

Normally I set that with something like:
```
(define-key isearch-mode-map (kbd "C-o") #'swiper-isearch-toggle)
(define-key swiper-map (kbd "C-o") #'swiper-isearch-toggle)
```

But when I enable this package's mode it does not work.

Same applies to commands like C-l to center the candidate and so on. This last one I understand is intended to not work because is a buffer action instead of a minibuffer one... but I mention just to assert it is intended.

**Comment by astoff** [comment]
Just to make sure we are on the same page: you are saying that you added `swiper-isearch-toggle` to the `iserach-mb--with-exit` list as explained [here](https://github.com/astoff/isearch-mb#interaction-with-other-isearch-extensions) and `C-o` still doesn't work? Also, the first define-key should be in `isearch-mb-minibuffer-map`.

As to second case, calling `swiper-isearch-toggle` from Swiper, I would have expected this to just work without any configuration. What happens instead?

Concerning recenter, there already exists the `minibuffer-recenter-top-bottom` for that. Maybe I should bind it in `isearch-mb-minibuffer-map`.
