### ISSUE TITLE
After pressing `isearch-forward-regexp` twice, the prompt becomes "Regexp Regexp I-search"

### ISSUE THREAD

**Issue by AmaiKinono** [astoff/isearch-mb#18]
I have `C-/` bound to `isearch-forward-regexp`. Here's what happens when I press it twice:

![image](https://user-images.githubusercontent.com/28714352/127359170-d39cd36b-da85-48cd-8910-9451b1411daa.png)

This is tested in `$ emacs -Q`, 27.2.

Recipe:

``` elisp
(require 'isearch-mb)
(isearch-mb-mode)
(global-set-key (kbd "C-/") 'isearch-forward-regexp)
;; Then press C-/ twice.
```

**Comment by astoff** [comment]
Okay, this enters some inconsistent state, but what did you expect to happen instead? You config also doesn't seem to make sense with the normal isearch either.

Perhaps you forgot to bind `C-/` to `isearch-repeat-forward` in `isearch-mb-minibuffer-map`?

**Comment by AmaiKinono** [comment]
I have `C-n` and `C-p` bound to `isearch-repeat-forward/backward`.

I know `isearch-forward-regexp` is not designed to be used in an isearch session (as `C-M-s` is bound to `isearch-repeat-forward` in `isearch-mode-map`), so I don't know what to expect too. But I think the prompt shouldn't be messed up.

**Comment by astoff** [comment]
Since this problem seem totally innocuous (the prompt gets back to normal after pressing some other key), I'll close the ticket.
