### ISSUE TITLE
Wrong lazy count info when starting the search

### ISSUE THREAD

**Issue by AmaiKinono** [astoff/isearch-mb#20]
The lazy count info is `0/total-count` when starting a search session. Only after we call `isearch-repeat-forward/backward`, the current count is not zero.

This also happens when we `isearch-repeat` in the opposite direction for the first time.

Recipe for `$ emacs -Q`:

``` elisp
(require 'isearch-mb)
(setq isearch-lazy-count t)
;; Then search for some words that exist in the buffer, the current count is not 0.
(isearch-mb-mode)
;; Now search again. The current count is 0.
```

**Comment by astoff** [comment]
Yes, I'm aware of this, and it's a problem in isearch.el from Emacs ≤ 27. I don't see this issue in Emacs 28, so I don't want to add workarounds for it. But if you see any similar issue with a newer version of isearch.el, please let me know.
