### ISSUE TITLE
Could input methods be made to work?

### ISSUE THREAD

**Issue by mattbeshara** [astoff/isearch-mb#23]
I'd like to use a Quail input method with isearch-mb.  Currently, when I enter a regular isearch where the input method works as expected, the prompt reads `Regexp I-search [\]:`
(The display name of the input method is `\`, it's a custom one I've put together, I just wanted the display name to be short).
This same prompt text as regular isearch displays is visible for a split second after starting a search using isearch-mb, but then it changes to just `Regexp I-search:`.  
Also, while in an isearch-mb search, pressing `C-\` seems to do nothing, whereas it toggles the input method on and off in regular buffers and the minibuffer when it is being used for something other than isearch-mb.
Do you happen to have any idea what might be going on here?  The only call made to `read-from-minibuffer` does specify `t` for `INHERIT-INPUT-METHOD`, so at first glance it seems like the code is doing the right thing, but I haven't spent too much time looking into this myself.

**Comment by astoff** [comment]
Input methods are supposed to work, of course, just like they normally work in the minibuffer. Unfortunately, it turns out that iseach hacks into the input methods. I'm looking for a way to undo these isearch kludges.

**Comment by mattbeshara** [comment]
Thank you!

**Comment by astoff** [comment]
Okay, I think I figured it out. Let me know if it works. (By the way, if you use the TeX input method, you might like my [unicode-math-input](https://github.com/astoff/unicode-math-input.el) package.)

**Comment by mattbeshara** [comment]
It works great!
