### ISSUE TITLE
Feature request: make `isearch-mb--no-search` part of the public API by renaming it and declaring it with `defcustom`

### ISSUE THREAD

**Issue by hab25** [astoff/isearch-mb#28]
The reason I want to customize it I have a function in `minibuffer-setup-hook` that inserts a string into the minibuffer. In the case of `isearch-mb` I don't want this automatic insertion to move point in the current buffer.

The reason I want it to be made part of the public API is so I can rely upon it such that it breaking would lead to the release of a backwards-incompatible semantic version (which I can programmatically check for).

**Comment by astoff** [comment]
Feel free to add things to this and other "private" variables. They are not public in the sense that they are not relevant for the regular user, i.e., you need to know what you are doing if you change them.
