### ISSUE TITLE
Feature request: option for indicating current the value of  `isearch-case-fold-search` and `isearch-regexp` in the `isearch-mb` minibuffer prompt

### ISSUE THREAD

**Issue by hab25** [astoff/isearch-mb#29]
I'm guessing `isearch-mb--update-prompt` would be the right place to implement this.

**Comment by astoff** [comment]
`isearch-regexp` is already shown, right? For case fold, see this: See this: https://github.com/astoff/isearch-mb/wiki#case-fold-info-in-isearch-mb-prompt

**Comment by hab25** [comment]
> `isearch-regexp` is already shown, right? 

Right, sorry.

> See this: [astoff/isearch-mb/wiki#case-fold-info-in-isearch-mb-prompt](https://github.com/astoff/isearch-mb/wiki#case-fold-info-in-isearch-mb-prompt)

Thanks. I agree with not adding that to `isearch-mb` as it seems quite fragile against future changes in `isearch`. 

I hope that `isearch` gets a persistent case-fold indication similar to the existing regexp one. Then, perhaps `isearch-mb` could integrate it.
