### ISSUE TITLE
Should require cl-lib at compile time because of cl-letf

### ISSUE THREAD

**Issue by minad** [astoff/isearch-mb#4]

**Comment by astoff** [comment]
I'm generally confused by these things. `cl-letf` is autoloaded (so why bother requiring?) in cl-macs.el, which is not required by cl-lib (the opposite dependency holds).

**Comment by minad** [comment]
I am also confused by this. However the bytecode compiler prints a warning.

~~~ sh
emacs -Q --eval '(byte-compile-file "isearch-mb.el")'
~~~

This should be fixed like this:

~~~ elisp
(eval-when-compile 
  (require 'cl-lib)
  (require 'subr-x))
~~~

**Comment by astoff** [comment]
Fixed in https://github.com/astoff/isearch-mb/commit/0b58b148804c138cdde305b63057baafe6ef4661.
