### ISSUE TITLE
Remap previous/next-line-or-history-element to isearch-repeat-backward/forward

### ISSUE THREAD

**Issue by minad** [astoff/isearch-mb#5]
Okay, so that's it from me ;)

**Comment by astoff** [comment]
I do that in my config, but wasn't sure it's to be considered a canonical thing to do...

**Comment by minad** [comment]
I think it would be a bit more user friendly to do this, since it aligns the behavior with consult-line in Vertico etc. You could also mention it only in the readme, in case you want to stay closer to the default bindings. On the other hand you already add quite a few bindings so I don't think it would hurt to add this too.

**Comment by astoff** [comment]
Do you agree with <kbd>C-j</kbd> for `newline` in the search minibuffer? How about the `isearch-beginning/end-of-buffer` bindings?
