### ISSUE TITLE
One more idea - better mode line indicator

### ISSUE THREAD

**Issue by minad** [astoff/isearch-mb#6]
I have something like this in my config, which is similar to what isearch+ does. It only works so lala because of the minibuffer-message sit-for delays. Maybe there is also more information which could be shown. Do you think something like this is within the scope of isearch-mb?

~~~ elisp
(defun dm/isearch-indicator-remove ()
  (setq mode-line-misc-info (delete "ISEARCH " mode-line-misc-info)
        mode-line-misc-info (delete "Isearch " mode-line-misc-info)
        mode-line-misc-info (delete "R*SEARCH " mode-line-misc-info)
        mode-line-misc-info (delete "R*search " mode-line-misc-info)))

(defun dm/isearch-indicator-update ()
  (dm/isearch-indicator-remove)
  (push (concat (propertize (if isearch-case-fold-search
                                (if isearch-regexp "R*SEARCH" "ISEARCH")
                              (if isearch-regexp "R*search" "Isearch"))
                            'face 'isearch)
                " ")
        mode-line-misc-info))

(add-hook 'isearch-mode-end-hook #'dm/isearch-indicator-remove)
(add-hook 'isearch-update-post-hook #'dm/isearch-indicator-update)
~~~

**Comment by astoff** [comment]
At some point I included this:
```elisp
(defvar isearch-mb--lighter
  '(" Isearch:"
    (search-spaces-regexp "s" "-")
    (isearch-case-fold-search "c" "-")
    (isearch-wrapped (:eval (if (and (not isearch-wrap-function)
			             (if isearch-forward
				         (> (point) isearch-opoint)
			               (< (point) isearch-opoint)))
		                "W" "w"))
                     "-"))
  "Mode line indicator for `isearch-mode'.")
```
But then I removed it, since I'm not really convinced this is better than nothing.

**Comment by minad** [comment]
I would love to have some isearch indicators which somehow expose the current configuration of the isearch. I must admit I didn't really know for a long time that isearch offers all these different modi. I think it could be helpful for many users, at least the ones who use Emacs intuitively and don't read the full docs. I used Emacs for many years, but I guess never to its full extent and power since I didn't look deeply into the details. It worked okay, but it would have been neat if there were more visual clues. I am not advocating to not read the docs, but I believe there could be some small improvements to lower the barriers.

**Comment by minad** [comment]
If you say that this feature is out of scope for isearch-mb, that is okay since it is more of an orthogonal concern. I just thought I mention it, assuming that isearch-mb aims to be an "improved isearch" package.

**Comment by astoff** [comment]
Maybe something like this
```elisp
(setf (cadr (assoc 'isearch-mode minor-mode-alist))
      '(""
        isearch-mode
        "/"
        (isearch-regexp
         "R"
         (isearch-regexp-function
          (:eval (upcase
                  (substring
                   (or (get isearch-regexp-function 'isearch-message-prefix) "?")
                   0 1)))
          "-"))
        (isearch-regexp (isearch-regexp-lax-whitespace "S" "-")
                        (isearch-lax-whitespace "S" "-"))
        (isearch-case-fold-search "C" "-")))
```
or like this?
``` elisp
(setf (cadr (assoc 'isearch-mode minor-mode-alist))
      '(""
        isearch-mode
        "/"        
        (isearch-regexp (isearch-regexp-lax-whitespace "S" "")
                        (isearch-lax-whitespace "S" ""))
        (isearch-case-fold-search "C" "")))
```

The first version would make the search mode info in the prompt technically redundant, but maybe removing the info from the prompt would be too much. What do you think?

**Comment by minad** [comment]
I like the first version showing more of the state at a single spot. Depends on preferences :shrug:

**Comment by astoff** [comment]
This is a general isearch question, so I will close the issue. (Improving the mode line indicator in Emacs itself would also allow to declutter the isearch echo area message.)

If you arrived at a solution you find useful, feel free to add it to the wiki.
